name: "Flex-Vers"
description: "A GitHub Action to run Flex-Vers from Dockerhub; Flex-Vers is a tool to manage versions of your project."
color: "green"
icon: "tag"
inputs:
  skip_non_formatted: 
    description: "Skip non-formatted versions"
    required: false
    default: "false"
    type: "boolean"
  force_release: 
    description: "Force release"
    required: false
    default: "false"
    type: "boolean"
  force_pre_release:
    description: "Force pre-release"
    required: false
    default: "false"
    type: "boolean"
  keep_root_version_up_to_date:
    description: "Keep root version up to date"
    required: false
    default: "false"
    type: "boolean"
  lint:
    description: "Lint the project"
    required: false
    default: "false"
    type: "boolean"
runs:
  using: "docker"
  image: "docker://bsmithcompsci/flex-vers:latest"
  entrypoint: "bash"
  args: 
  - "entrypoint.sh"