name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - uses: actions/checkout@v4

    # Linting with Clippy; Clippy is a collection of lints to catch common mistakes and improve your Rust code.
    - name: Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

    # Run tests
    - name: Run tests
      run: cargo test --verbose

    # Build the project and publish it to Dockerhub
    - name: Publish to Dockerhub
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        repository: ${{ secrets.DOCKERHUB_USERNAME }}/flex-vers 
        tags: latest, ${{ github.sha }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
